# openssl passwd -apr1 ${password} | base64
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-radio-auth
  labels:
    {{- template "radio.labels" . }}
data:
  {{- range $key, $val := .Values.auth }}
  {{ $key }}: {{ tpl $val $ | quote }}
  {{- end -}}