- name: Populate service facts
  service_facts:

- name: disable track_update
  ansible.builtin.service:
    name: track_update
    state: stopped
    daemon_reload: true
    enabled: false
  when: "'track_update' in services"